version: '3.3'
services:
  build:
    image: ubuntu:18.04
    volumes:
      - ../:/minishogilib
    command: >
        bash -c "apt update &&
              apt-get install -y curl python3-pip python3.7 &&
              curl https://sh.rustup.rs -sSf | sh -s -- -y &&
              pip3 install pyo3-pack &&
              source /root/.cargo/env &&
              rustup default nightly &&
              cd minishogilib/ &&
              pyo3-pack build"
