name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      script: |
        rustup install nightly
        rustup override set nightly
        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
