name: Rust

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: |
          rustup install nightly
          rustup override set nightly
          cargo test --release --verbose
