name: wheel

on: [push]

jobs:
  wheel:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7 on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Set up Python 3.8 on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Set up Python 3.9 on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set up Python 3.10 on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Python 3.11 on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Set up Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Enable Rust
        run: |
          source "$HOME/.cargo/env"
      - name: Install maturin
        run: |
          pip3 install maturin
      - name: Set up zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Build wheel
        if: matrix.os == 'ubuntu-latest'
        run: |
          maturin build --release --zig
      - name: Build wheel
        if: matrix.os == 'macos-latest'
        run: |
          maturin build --release --universal2
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: ./target/wheels/
