name: wheel

on: [push]

jobs:
  wheel:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7 on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Set up Python 3.8 on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Set up Python 3.9 on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set up Python 3.10 on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Python 3.11 on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
      - name: Set up rustup
        if: matrix.os = 'ubuntu-latest'
        run: |
          rustup target add x86_64-unknown-linux-gnu
      - name: Set up rustup
        if: matrix.os == 'macos-latest'
        run: |
          rustup target add aarch64-apple-darwin x86_64-apple-darwin
      - name: Install maturin
        run: |
          pip3 install maturin
      - name: Build wheel
        run: |
          maturin build --release --manylinux 2014
      - name: auditwheel
        run: |
          pip3 install auditwheel
          mkdir -p manylinux_wheel/ && auditwheel repair ./target/wheels/*.whl -w manylinux_wheel/
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: manylinux_wheel/
