name: wheel

on: [push]

jobs:
  wheel:
    runs-on: ubuntu:18.04
    steps:
      - uses: actions/checkout@v1
      - name: Wheel
        run: |
          cd docker
          docker-compose up build
          cd ../
          mkdir /minishogilib
          cp t./arget/wheels/* /minishogilib/          
      - uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: /minishogilib/
