name: wheel

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
      - name: Install maturin
        run: |
          pip3 install maturin
      - name: Build wheel
        run: |
          maturin build --release
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: ./target/wheels/
      - name: Copy artifacts into dist
        run:
          mkdir -p dist/ && cp ./target/wheels/*.whl dist/
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: '__token__'
          password: ${{ secrets.PYPI_API_TOKEN }}
